// <auto-generated />
using System;
using APINEW.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APINEW.Migrations
{
    [DbContext(typeof(NewApiApplicationContext))]
    [Migration("20240814093358_Initial db operation")]
    partial class Initialdboperation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APINEW.DATA.SoldToursEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Tourid")
                        .HasColumnType("integer");

                    b.Property<int>("Userid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Tourid");

                    b.ToTable("SoldTours");
                });

            modelBuilder.Entity("APINEW.DATA.ToursEntity", b =>
                {
                    b.Property<int>("kitapid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("kitapid"));

                    b.Property<string>("kitapAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("sayfa")
                        .HasColumnType("integer");

                    b.Property<string>("tur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("yazar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("kitapid");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("APINEW.DATA.SoldToursEntity", b =>
                {
                    b.HasOne("APINEW.DATA.ToursEntity", "tour")
                        .WithMany()
                        .HasForeignKey("Tourid");

                    b.Navigation("tour");
                });
#pragma warning restore 612, 618
        }
    }
}
